version: "3.8"

services:
  app:
    container_name: app
    image: node:16-alpine
    working_dir: /app
    entrypoint: /bin/sh
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - .:/app
    tty: true
